<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251129112925 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX membre_email_key');
        $this->addSql('ALTER TABLE membre ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE membre ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE membre ALTER telephone SET NOT NULL');
        $this->addSql('ALTER TABLE membre ALTER username TYPE VARCHAR(180)');
        $this->addSql('ALTER TABLE membre ALTER role TYPE JSON');
        $this->addSql('ALTER TABLE membre ALTER role DROP DEFAULT');
        $this->addSql('ALTER INDEX membre_username_key RENAME TO UNIQ_F6B4FB29F85E0677');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE membre ALTER id SET DEFAULT nextval(\'membre_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE membre ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE membre ALTER telephone DROP NOT NULL');
        $this->addSql('ALTER TABLE membre ALTER username TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE membre ALTER role TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE membre ALTER role SET DEFAULT \'ROLE_USER\'');
        $this->addSql('CREATE UNIQUE INDEX membre_email_key ON membre (email)');
        $this->addSql('ALTER INDEX uniq_f6b4fb29f85e0677 RENAME TO membre_username_key');
    }
}
