name: Full Security Scan
on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  trufflehog:
    uses: ./.github/workflows/security-trufflehog.yml
  trivy:
    uses: ./.github/workflows/security-trivy.yml
  semgrep:
    uses: ./.github/workflows/security-semgrep.yml
